### ISSUE TITLE
Add user to locator_ros_bridge-release

### ISSUE THREAD

**Issue by slaible** [ros2-gbp/locator_ros_bridge-release#1]
Hi @nuclearsandwich,

Could you add the user @kfabian to this repository so that he can also release packages with bloom-release? Thanks in advance!

**Comment by slaible** [comment]
Hi @nuclearsandwich,

Could you add the users @kfabian and @syyuen to this repository so that they can release packages with bloom-release? At least @syyuen does not have permissions. The same would also be necessary for the ROS1 version: https://github.com/ros-gbp/locator_ros_bridge-release. I hope this is the right place for asking.

**Comment by nuclearsandwich** [comment]
Wow, sorry I missed the original opening of this issue. I've opened https://github.com/ros2-gbp/ros2-gbp-github-org/pull/212 to address the request. In the future, it will be more reliable to open permissions issues directly on the https://github.com/ros2-gbp/ros2-gbp-github-org/ repository. Thanks!

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Comment by slaible** [comment]
@nuclearsandwich What would be the right place for an issue for the ROS 1 version? I now placed it here: https://github.com/ros-gbp/locator_ros_bridge-release/issues/1
